# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPostWithHeader',
            fields=[
                ('basicpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.BasicPost')),
                ('title', models.CharField(max_length=200)),
            ],
            bases=('common.basicpost',),
        ),
    ]
