# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_basicpostwithheader'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasicPostWithHeader',
            new_name='TitledBasicPost',
        ),
    ]
