# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20160825_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpost',
            name='body_html',
            field=models.TextField(default='not updated yet'),
            preserve_default=False,
        ),
    ]
