# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_basicpost_body_html'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavMenuItem',
        ),
    ]
