# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('markdownmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.MarkdownModel')),
                ('position', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('short_desc', models.CharField(max_length=1500)),
                ('thumbnail', models.ImageField(upload_to='images/thumbnails')),
            ],
            bases=('common.markdownmodel',),
        ),
        migrations.CreateModel(
            name='EquipmentGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('info', models.TextField()),
                ('image', models.ImageField(upload_to='images/galleries')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
