# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_auto_20160825_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description_brief', models.CharField(max_length=1500)),
                ('thumbnail', models.ImageField(upload_to='images/thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='image')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentLongDescriptionSection',
            fields=[
                ('titledbasicpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.TitledBasicPost')),
                ('position', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
            ],
            bases=('common.titledbasicpost',),
        ),
    ]
