# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_auto_20160822_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description_brief', models.CharField(max_length=1500)),
                ('thumbnail', models.ImageField(upload_to='images/thumbnails')),
                ('description_long', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.TitledBasicPost')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentGalleryImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Image')),
                ('position', models.PositiveIntegerField()),
                ('gallery_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
            ],
            bases=('common.image',),
        ),
    ]
