# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_basicpost_body_html'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentlongdescriptionsection',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='equipmentlongdescriptionsection',
            name='titledbasicpost_ptr',
        ),
        migrations.DeleteModel(
            name='EquipmentLongDescriptionSection',
        ),
    ]
