# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20160822_0207'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLongDescriptionSection',
            fields=[
                ('titledbasicpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.TitledBasicPost')),
            ],
            bases=('common.titledbasicpost',),
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='description_long',
        ),
        migrations.AddField(
            model_name='equipmentlongdescriptionsection',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment'),
        ),
    ]
