# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20160825_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentlongdescriptionsection',
            name='position',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
