# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_basicpost_body_html'),
        ('equipment', '0002_auto_20160901_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLongDescription',
            fields=[
                ('basicpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.BasicPost')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
            ],
            bases=('common.basicpost',),
        ),
    ]
