# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipmentlongdescriptionsection_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentgalleryimage',
            name='gallery_subject',
        ),
        migrations.RemoveField(
            model_name='equipmentgalleryimage',
            name='image_ptr',
        ),
        migrations.DeleteModel(
            name='EquipmentGalleryImage',
        ),
    ]
