# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20160825_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='image')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
            ],
        ),
    ]
