# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 20:15
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('section_title', models.CharField(max_length=150)),
                ('section_content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
