# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'ordering': ['position', 'section_title']},
        ),
    ]
