# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20160629_0146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutSection',
            new_name='AboutSectionOld',
        ),
    ]
