# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_aboutsectoin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutSectoin',
            new_name='AboutSection',
        ),
    ]
