# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20160822_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSectionOld',
        ),
    ]
