# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('markdownmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.MarkdownModel')),
                ('title', models.CharField(max_length=250)),
                ('position', models.PositiveIntegerField()),
            ],
            bases=('common.markdownmodel',),
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('display_text', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['position', 'display_text'],
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faqs.FaqCategory'),
        ),
    ]
