# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-27 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0005_basicpost_body_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('titledbasicpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.TitledBasicPost')),
                ('position', models.PositiveIntegerField()),
            ],
            bases=('common.titledbasicpost',),
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('display_text', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['position', 'display_text'],
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='faqs.FaqCategory'),
        ),
    ]
