# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_auto_20160623_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='faqs.FaqCategory'),
        ),
    ]
