# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_auto_20160623_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question_text',
            field=models.CharField(max_length=250),
        ),
    ]
