# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 20:15
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0004_auto_20160623_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
