# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0005_auto_20160628_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ['position', 'display_text']},
        ),
    ]
