# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0006_auto_20160629_0146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faq',
            new_name='FaqOld',
        ),
    ]
