# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20160822_0207'),
        ('faqs', '0007_auto_20160824_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqNew',
            fields=[
                ('titledbasicpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.TitledBasicPost')),
                ('position', models.PositiveIntegerField()),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='faqs.FaqCategory')),
            ],
            bases=('common.titledbasicpost',),
        ),
    ]
