# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0008_faqnew'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaqNew',
            new_name='Faq',
        ),
    ]
