# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('markdownmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.MarkdownModel')),
                ('position', models.PositiveIntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('short_desc', models.TextField()),
                ('completion_date', models.DateField(null=True)),
                ('thumbnail', models.ImageField(upload_to='products/images/thumbnails')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
            bases=('common.markdownmodel',),
        ),
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
