# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('short_desc', models.TextField()),
                ('long_desc', models.TextField()),
                ('completion_date', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='products/images/thumbnails')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('info', models.TextField()),
                ('image', models.ImageField(upload_to='products/images/galleries')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
