# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgalleryimage',
            name='image',
            field=models.ImageField(default=0, upload_to='images/galleries'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productgalleryimage',
            name='info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productgalleryimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productgalleryimage',
            name='title',
            field=models.CharField(default='title', max_length=500),
            preserve_default=False,
        ),
    ]
