# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='completion_date',
            field=models.DateField(null=True),
        ),
    ]
